create table public.bank_logs (
  id serial not null,
  user_id text null,
  username text null,
  quantidade bigint null,
  tipo text null,
  motivo text null,
  data timestamp with time zone null default now(),
  constraint bank_logs_pkey primary key (id)
) TABLESPACE pg_default;

create table public.active_channels (
  channel_id bigint not null,
  constraint active_channels_pkey primary key (channel_id)
) TABLESPACE pg_default;

create table public.bank_balance (
  id text not null default 'global'::text,
  gemas bigint null default 0,
  constraint bank_balance_pkey primary key (id)
) TABLESPACE pg_default;

create table public.parcerias (
  invite_code text not null,
  role_id bigint not null,
  tag text not null,
  clan_name text not null,
  created_at timestamp with time zone null default now(),
  constraint parcerias_pkey primary key (invite_code)
) TABLESPACE pg_default;

create table public.protected_users (
  user_id bigint not null,
  created_at timestamp with time zone null default now(),
  constraint protected_users_pkey primary key (user_id)
) TABLESPACE pg_default;

create table public.recruitments (
  id uuid not null default gen_random_uuid (),
  recruiter_id text null,
  recruit_roblox_name text null,
  recruit_roblox_nick text null,
  recruit_age text null,
  recruit_discord_nick text null,
  gender text null,
  platform text null,
  created_at timestamp with time zone null default now(),
  recruit_id text null,
  recruit_image text null,
  registro_id bigint generated by default as identity not null,
  saidas_count bigint null default '0'::bigint,
  constraint recruitments_pkey primary key (id, registro_id)
) TABLESPACE pg_default;

create table public.stats (
  id text not null,
  total_translations bigint null default 0,
  constraint stats_pkey primary key (id)
) TABLESPACE pg_default;

create table public.user_stats (
  user_id bigint not null,
  xp integer null default 0,
  username text null,
  preferred_lang text null default 'Não definido'::text,
  birthday text null,
  constraint user_stats_pkey primary key (user_id)
) TABLESPACE pg_default;

-- ---------------------------------------------------------------------------
-- Sistema de Prints (v2.8)
-- ---------------------------------------------------------------------------

-- Configuração por servidor: canal onde os prints são recebidos/avisados
create table public.print_config (
  guild_id bigint not null,
  review_channel_id bigint null,
  daily_limit integer null default 2,
  created_at timestamp with time zone null default now(),
  constraint print_config_pkey primary key (guild_id)
) TABLESPACE pg_default;

-- Cargos elegíveis que podem ser concedidos numa print "por elo"
create table public.print_roles (
  id serial not null,
  guild_id bigint not null,
  role_id bigint not null,
  created_at timestamp with time zone null default now(),
  constraint print_roles_pkey primary key (id)
) TABLESPACE pg_default;

-- Prints enviadas pelos usuários para análise
create table public.print_submissions (
  id serial not null,
  user_id text null,
  username text null,
  tipo text null,
  image_url text null,
  status text null default 'pendente'::text,
  motivo_recusa text null,
  granted_role_id bigint null,
  reviewed_by text null,
  created_at timestamp with time zone null default now(),
  constraint print_submissions_pkey primary key (id)
) TABLESPACE pg_default;

